### ISSUE TITLE
Upload ignores bucket in the URL

### ISSUE THREAD

**Issue by tkilias** [exasol/bucketfs-client#5]
If I run the following command 

`java -cp bfsc-0.1.0.jar com.exasol.bucketfs.client.BucketFsClient cp -p bfsc-0.1.0.jar bfs://localhost:6666/default/test1/`

it produces the following error

`E-BFSJ-1: Unable do upload http://localhost:6666/test/bfsc-0.1.0.jar. HTTP status 400.`

If I instead run the following command where I doubled the bucket

`java -cp bfsc-0.1.0.jar com.exasol.bucketfs.client.BucketFsClient cp -p bfsc-0.1.0.jar bfs://localhost:6666/default/default/test1/`

It is afterwards available at `http://localhost:6666/default/test1/bfsc-0.1.0.jar`

**Comment by redcatbear** [comment]
I see where the confusion comes from. The first `default` is actually the name of the BucketFS service.

Now that I think about it, it probably does not make to much sense in the URL since that service name is just another way to express the port number on BucketFS.

Removing the port number is not a good idea, because then you don't have a standard-compliant URL anymore if the port is silently changed. So the best option is to remove the service name from the URL.
